tinyMCE.addI18n('ru.media_dlg', {
    title: "Вставить/редактировать медиа-объект",
    general: "Общие",
    advanced: "Дополнительные",
    file: "Файл/адрес",
    list: "Список",
    size: "Размеры",
    preview: "Предварительный просмотр",
    constrain_proportions: "Сохранять пропорции",
    type: "Тип",
    id: "Идентификатор",
    name: "Название",
    class_name: "Класс",
    vspace: "Вертикальное пространство",
    hspace: "Горизонтальное пространство",
    play: "Проигрывать автоматически",
    loop: "Зациклить",
    menu: "Отобразить меню",
    quality: "Качество",
    scale: "Масштаб",
    align: "Выравнивание",
    salign: "SAlign",
    wmode: "WMode",
    bgcolor: "Фон",
    base: "Основа",
    flashvars: "Flashvars",
    liveconnect: "SWLiveConnect",
    autohref: "AutoHREF",
    cache: "Кэш",
    hidden: "Скрытое",
    controller: "Controller",
    kioskmode: "Kiosk mode",
    playeveryframe: "Play every frame",
    targetcache: "Target cache",
    correction: "No correction",
    enablejavascript: "Enable JavaScript",
    starttime: "Start time",
    endtime: "End time",
    href: "Href",
    qtsrcchokespeed: "Choke speed",
    target: "Target",
    volume: "Громкость",
    autostart: "Auto start",
    enabled: "Enabled",
    fullscreen: "Fullscreen",
    invokeurls: "Invoke URLs",
    mute: "Беззвучно",
    stretchtofit: "Stretch to fit",
    windowlessvideo: "Windowless video",
    balance: "Balance",
    baseurl: "Base URL",
    captioningid: "Captioning id",
    currentmarker: "Current marker",
    currentposition: "Current position",
    defaultframe: "Default frame",
    playcount: "Play count",
    rate: "Rate",
    uimode: "UI Mode",
    flash_options: "Flash options",
    qt_options: "Quicktime options",
    wmp_options: "Windows media player options",
    rmp_options: "Real media player options",
    shockwave_options: "Shockwave options",
    autogotourl: "Auto goto URL",
    center: "Center",
    imagestatus: "Image status",
    maintainaspect: "Maintain aspect",
    nojava: "No java",
    prefetch: "Prefetch",
    shuffle: "Shuffle",
    console: "Console",
    numloop: "Num loops",
    controls: "Controls",
    scriptcallbacks: "Script callbacks",
    swstretchstyle: "Stretch style",
    swstretchhalign: "Stretch H-Align",
    swstretchvalign: "Stretch V-Align",
    sound: "Sound",
    progress: "Progress",
    qtsrc: "QT Src",
    qt_stream_warn: "Streamed rtsp resources should be added to the QT Src field under the advanced tab.\nYou should also add a non streamed version to the Src field..",
    align_top: "Top",
    align_right: "Right",
    align_bottom: "Bottom",
    align_left: "Left",
    align_center: "Center",
    align_top_left: "Top left",
    align_top_right: "Top right",
    align_bottom_left: "Bottom left",
    align_bottom_right: "Bottom right",
    flv_options: "Flash video options",
    flv_scalemode: "Scale mode",
    flv_buffer: "Buffer",
    flv_startimage: "Start image",
    flv_starttime: "Start time",
    flv_defaultvolume: "Default volumne",
    flv_hiddengui: "Hidden GUI",
    flv_autostart: "Auto start",
    flv_loop: "Loop",
    flv_showscalemodes: "Show scale modes",
    flv_smoothvideo: "Smooth video",
    flv_jscallback: "JS Callback"
});