tinyMCE.addI18n('ru.xhtmlxtras_dlg', {
    attribute_label_title: "Название",
    attribute_label_id: "Идентификатор",
    attribute_label_class: "Класс",
    attribute_label_style: "Стиль",
    attribute_label_cite: "Цитата",
    attribute_label_datetime: "Дата/время",
    attribute_label_langdir: "Направление текста",
    attribute_option_ltr: "Слева направо",
    attribute_option_rtl: "Справа налево",
    attribute_label_langcode: "Язык",
    attribute_label_tabindex: "Индекс табуляции",
    attribute_label_accesskey: "Клавиша доступа",
    attribute_events_tab: "События",
    attribute_attrib_tab: "Атрибуты",
    general_tab: "Общие",
    attrib_tab: "Атрибуты",
    events_tab: "События",
    fieldset_general_tab: "Общие настройки",
    fieldset_attrib_tab: "Атрибуты элемента",
    fieldset_events_tab: "События элемента",
    title_ins_element: "Элемент добавленного текста",
    title_del_element: "Элемент удалённого текста",
    title_acronym_element: "Элемент акронима",
    title_abbr_element: "Элемент аббревиатуры",
    title_cite_element: "Элемент цитаты",
    remove: "Убрать",
    insert_date: "Вставить текущую дату/время",
    option_ltr: "Слева направо",
    option_rtl: "Справа налево",
    attribs_title: "Вставить/редактировать атрибуты"
});