tinyMCE.addI18n('ru.advlink_dlg', {
    title: "Вставить/редактировать ссылку",
    url: "Адрес ссылки",
    target: "Цель",
    titlefield: "Название",
    is_email: "Введённый адрес похож на email, вы хотите добавить префикс mailto:?",
    is_external: "Введённый адрес похож на внешнюю ссылку, вы хотите добавить префикс http://?",
    list: "Список ссылок",
    general_tab: "Общие",
    popup_tab: "Всплывающее окно",
    events_tab: "События",
    advanced_tab: "Дополнительные",
    general_props: "Общие свойства",
    popup_props: "Свойства всплывающего окна",
    event_props: "События",
    advanced_props: "Дополнительные свойства",
    popup_opts: "Параметры",
    anchor_names: "Якоря",
    target_same: "Открыть в этом окне / фрейме",
    target_parent: "Открыть в родительском окне / фрейме",
    target_top: "Открыть в верхнем фрейме (замещает все остальные)",
    target_blank: "Открыть в новом окне",
    popup: "Всплывающее JavaScript-окно",
    popup_url: "Адрес всплывающего окна",
    popup_name: "Название окна",
    popup_return: "Вставить 'return false'",
    popup_scrollbars: "Показать полосы прокрутки",
    popup_statusbar: "Показать строку состояния",
    popup_toolbar: "Показать панели инструментов",
    popup_menubar: "Показать строку меню",
    popup_location: "Показать строку адреса",
    popup_resizable: "Сделать размер окна изменяемым",
    popup_dependent: "Зависимые (только Mozilla/Firefox)",
    popup_size: "Размер",
    popup_position: "Позиция (X/Y)",
    id: "Идентификатор",
    style: "Стиль",
    classes: "Классы",
    target_name: "Название цели",
    langdir: "Направление языка",
    target_langcode: "Целевой язык",
    langcode: "Код языка",
    encoding: "Целевая кодировка",
    mime: "Целевой MIME-тип",
    rel: "Отношение страница к цели",
    rev: "Отношение цель к странице",
    tabindex: "Индекс табуляции",
    accesskey: "Клавиша доступа",
    ltr: "Слева направо",
    rtl: "Справа налево",
    link_list: "Список ссылок"
});