tinyMCE.addI18n('ru.advanced', {
    style_select: "Стили",
    font_size: "Размер шрифта",
    fontdefault: "Шрифт",
    block: "Формат",
    paragraph: "Абзац",
    div: "Раздел",
    address: "Адрес",
    pre: "Отформатированный",
    h1: "Заголовок 1",
    h2: "Заголовок 2",
    h3: "Заголовок 3",
    h4: "Заголовок 4",
    h5: "Заголовок 5",
    h6: "Заголовок 6",
    blockquote: "Блок цитаты",
    code: "Код",
    samp: "Пример кода",
    dt: "Определяемый термин",
    dd: "Определение термина",
    bold_desc: "Полужирный (Ctrl+B)",
    italic_desc: "Курсив (Ctrl+I)",
    underline_desc: "Подчёркнутый (Ctrl+U)",
    striketrough_desc: "Перечёркнутый",
    justifyleft_desc: "Выравнивание влево",
    justifycenter_desc: "Выравнивание по центру",
    justifyright_desc: "Выравнивание вправо",
    justifyfull_desc: "Выравнивание по ширине",
    bullist_desc: "Маркированный список",
    numlist_desc: "Нумерованный список",
    outdent_desc: "Уменьшить отступ",
    indent_desc: "Увеличить отступ",
    undo_desc: "Отменить (Ctrl+Z)",
    redo_desc: "Повторить (Ctrl+Y)",
    link_desc: "Вставить/редактировать ссылку",
    unlink_desc: "Удалить ссылку",
    image_desc: "Вставить/редактировать изображение",
    cleanup_desc: "Почистить кривой код",
    code_desc: "Редактировать HTML-исходник",
    sub_desc: "Нижний индекс",
    sup_desc: "Верхний индекс",
    hr_desc: "Вставить горизонтальную линию",
    removeformat_desc: "Убрать форматирование",
    custom1_desc: "Введите ваше описание",
    forecolor_desc: "Выбрать цвет текста",
    backcolor_desc: "Выбрать цвет фона",
    charmap_desc: "Вставить специальный символ",
    visualaid_desc: "Включить/выключить направляющие/невидимые элементы",
    anchor_desc: "Вставить/редактировать якорь",
    cut_desc: "Вырезать",
    copy_desc: "Копировать",
    paste_desc: "Вставить",
    image_props_desc: "Свойства изображения",
    newdocument_desc: "New document",
    help_desc: "Help",
    blockquote_desc: "Блок цитаты",
    clipboard_msg: "Копирование/Вставка не работает в Mozilla и Firefox.\r\nХотите подробнее узнать, в чём дело?",
    path: "Path",
    newdocument: "Вы уверены, что хотите очистить всё содержимое?",
    toolbar_focus: "Перейти к кнопкам инструментов - Alt+Q, Перейти к редактору - Alt-Z, Перейти к пути элемента - Alt-X",
    more_colors: "Ещё цвета"
});